select *
from public.fy2015_districts_metrics_fy2016_methods_m


/* Crusher Materialized: https://github.com/educationsuperhighway/ficher/blob/master/Views/Materialized/2016%20Material%20Girl%20Equivalents/fy2016_districts_deluxe_m.sql
Crusher Standard: https://github.com/educationsuperhighway/ficher/blob/master/Views/Standard/2016%20Material%20Girl%20Equivalents/fy2016_districts_deluxe.sql
Material Girl Endpoint: https://github.com/educationsuperhighway/ecto/blob/master/db_ecto/material_girl/endpoint/fy2016_districts_deluxe.sql
*/
