select *
from endpoint.fy2016_services_received
where broadband = true



/* Crusher Materialized: https://github.com/educationsuperhighway/ficher/blob/master/Views/Materialized/2016%20Material%20Girl%20Equivalents/fy2016_services_received_m.sql
Crusher Standard: https://github.com/educationsuperhighway/ficher/blob/master/Views/Standard/2016%20Material%20Girl%20Equivalents/fy2016_services_received.sql
Material Girl Endpoint: https://github.com/educationsuperhighway/ecto/blob/master/db_ecto/material_girl/endpoint/fy2016_services_received.sql
*/