select erate, recipient_postal_cd, bandwidth_in_mbps, connect_category,
 purpose,line_item_recurring_elig_cost,line_item_total_num_lines,line_item_id
 from public.fy2017_services_received_matr sr
 where recipient_include_in_universe_of_districts
