insert into outlier_use_case_details (outlier_use_case_id,use_case_name,outlier_use_case_params,outlier_test_case_params,create_dt)
      values(10,'Increase in $/BW Rule','','',current_timestamp),
(11,'Decrease BW Not Meeting Connectivity','','',current_timestamp),
(12,'Increase Cost/Mbps Not Meeting Affordability','','',current_timestamp),
(13,'Increase in $/BW Rule','','',current_timestamp),
(14,'Decrease BW Not Meeting Connectivity','','',current_timestamp),
(15,'Increase Cost/Mbps Not Meeting Affordability','','',current_timestamp);
