insert into outlier_use_cases (outlier_use_case_name,outlier_use_case_cd,create_dt)
      values ('Cost per Circuit','cost_per_circuit',current_timestamp),
('Change in Total BW','change_in_total_bw',current_timestamp),
('% Change in BW','%_change_in_bw',current_timestamp),
('% Change in Monthly Cost','%_change_in_monthly_cost',current_timestamp),
('Monthly Cost per Mbps','monthly_cost_per_mbps',current_timestamp),
('BW per Student','bw_per_student',current_timestamp),
('Change in Total Monthly Cost','change_in_total_monthly_cost',current_timestamp);
